name: Qodana Overly Complex Method Analysis

on:
  push:
    branches: ["main"]
    pull_request:

  jobs:
    qodana:
      runs-on:
        ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Qodana CLI
          uses: jetbrains/qodana-action@v2024.1
          with:
            version: 2024.1

        - name: Run Qodana Analysis
          uses: jetbrains/qodana-action@v2024.1
          with:
              profile: qodana.recommended
              save-report: true
              fail-treshold: 1

        - name: Upload Qodana Results
          uses: actions/upload-artifact@v4
          with:
            name: qodana-report
            path: qodana/results


